name: Build and Push Github Action Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:

    build:
        name: Build to GCP docker registry
        runs-on: self-hosted
        env:
         IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
         PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

        steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v0'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .

        - name: Automatic Tagging of Releases
          id: increment-git-tag
          run: |
            bash ./scripts/counter_tag.sh -v major
        - name: Configure Docker Client
          run: |-
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker us-west2-docker.pkg.dev --quiet
        - name: Push Docker Image to Container Registry (GCR)
          env:
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |-
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
            
            
    deploy:
        name: Deploy to GCP run
        needs: build
        runs-on: self-hosted
 
        env:
         IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
         PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
         GCP_PROJECT_ID_DEPLOY: ${{ secrets.GCP_PROJECT_ID_DEPLOY }}
         
        steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Deploy to Cloud Run'
          run: |-
            gcloud run deploy $GCP_PROJECT_ID_DEPLOY \
             --region us-central1 \
              --image  gcr.io/$PROJECT_ID/$IMAGE_NAME  \
              --platform managed \
              --project=$PROJECT_ID               

